[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Vinci-GitHub <learning.never.exhausts.the.mind9@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
